[build]
publish = "public"
command = "hugo --themesDir=themes/hugo-coder --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.76.5"
HUGO_THEME = "hugo-coder"

[context.deploy-preview]
command = "hugo --themesDir=themes/hugo-coder --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
